export const Config = {
  URL: 'http://localhost:3000/',
  API_URL: 'http://localhost:3001/',
  SECURE_COOKIES_DOMAIN: 'localhost',
  IS_SITE_SECURE: false,
  P_SALT: 'addadf#d#FFhf#q3d843',
  EMAIL_FROM: 'dev@wykaz-sie.pl',
  EMAIL_USER: 'dev@wykaz-sie.pl',
  EMAIL_PASS: 'Ud623ccxyPBck4p',
  EMAIL_HOST: 'smtp.gmail.com',
  EMAIL_IS_SECURE: false,
  EMAIL_HOST_USE_POOLING: true,
  MAIN_ADMIN_EMAIL: 'michal.larysz91@gmail.com',
  MAIN_TECHNICAL_EMAIL: 'michal.larysz91@gmail.com',
  STOR_DIRECTORY: '__dirname/../stor/',
  COMPANY_NAME: 'Shooter',
  DB_CONNECTION: 'mongodb://localhost/shooter',
  ASSETS_DIRECTORY: '__dirname/../../assets/',
  SERVER_TIME_OFFSET: 0,
  DATABASE_TIME_OFFSET: 0,
  ANTI_FRAUD_MAX_TELS_PER_5_MINUTES: 75,
  VALID_CORS_ORIGIN: true,
};
